/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chat */

#ifndef _Included_chat
#define _Included_chat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chat
 * Method:    TTS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_chat_TTS
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
